### ISSUE TITLE
程序崩溃(分区导航-影视-剧集)

### ISSUE THREAD

**Issue by yihaha** [succlz123/AxBTube#6]
Process: org.succlz123.blueboard.app, PID: 6429
                                                                           java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
                                                                               at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                               at java.util.ArrayList.get(ArrayList.java:308)
                                                                               at org.succlz123.blueboard.view.adapter.recyclerview.AcPartitionRvAdapter.onBindViewHolder(AcPartitionRvAdapter.java:196)

**Comment by succlz123** [comment]
acfun变更过api，我还没做对应修改。
